services:
  web:
    container_name: web
    build: web
    ports:
      - '3030:3030'
    volumes:
      - ./web/:/web/
      - /web/node_modules/
    environment:
      - VITE_API_URL=http://app:8000
    depends_on:
      - app
    networks:
      - app-network

  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./app/:/app/
      - /app/instance/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules_web: